export let pivot_flatdata: { [key: string]: Object }[] = [
    { Amount: 2100, Country: "Canada", Date: "FY 2005", Product: "Bike", Quantity: 22, State: "Alberta" },
    { Amount: 1500, Country: "Canada", Date: "FY 2006", Product: "Van", Quantity: 28, State: "Alberta" },
    { Amount: 1060, Country: "Canada", Date: "FY 2007", Product: "Car", Quantity: 26, State: "Alberta" },
    { Amount: 5100, Country: "Canada", Date: "FY 2008", Product: "Car", Quantity: 21, State: "Alberta" },
    { Amount: 3100, Country: "Canada", Date: "FY 2005", Product: "Bike", Quantity: 40, State: "Quebec" },
    { Amount: 2000, Country: "Canada", Date: "FY 2006", Product: "Van", Quantity: 82, State: "Quebec" },
    { Amount: 4800, Country: "France", Date: "FY 2005", Product: "Car", Quantity: 49, State: "Charente-Maritime" },
    { Amount: 8100, Country: "France", Date: "FY 2006", Product: "Van", Quantity: 93, State: "Charente-Maritime" },
    { Amount: 2350, Country: "France", Date: "FY 2007", Product: "Bike", Quantity: 46, State: "Essonne" },
    { Amount: 7250, Country: "France", Date: "FY 2008", Product: "Van", Quantity: 43, State: "Essonne" },
    { Amount: 9450, Country: "France", Date: "FY 2007", Product: "Bike", Quantity: 49, State: "Gers" },
    { Amount: 1450, Country: "France", Date: "FY 2008", Product: "Car", Quantity: 49, State: "Gers" },
    { Amount: 3400, Country: "Germany", Date: "FY 2005", Product: "Van", Quantity: 78, State: "Bayern" },
    { Amount: 8400, Country: "Germany", Date: "FY 2006", Product: "Van", Quantity: 90, State: "Bayern" },
    { Amount: 5330, Country: "Germany", Date: "FY 2007", Product: "Car", Quantity: 45, State: "Hamburg" },
    { Amount: 5800, Country: "Germany", Date: "FY 2008", Product: "Bike", Quantity: 58, State: "Hamburg" },
    { Amount: 5700, Country: "Germany", Date: "FY 2006", Product: "Car", Quantity: 39, State: "Saarland" },
    { Amount: 5200, Country: "Germany", Date: "FY 2008", Product: "Car", Quantity: 48, State: "Saarland" },
    { Amount: 1040, Country: "United Kingdom", Date: "FY 2005", Product: "Bike", Quantity: 47, State: "England" },
    { Amount: 3380, Country: "United Kingdom", Date: "FY 2006", Product: "Car", Quantity: 75, State: "England" },
    { Amount: 5820, Country: "United Kingdom", Date: "FY 2007", Product: "Van", Quantity: 39, State: "England" },
    { Amount: 4820, Country: "United Kingdom", Date: "FY 2008", Product: "Bike", Quantity: 72, State: "England" },
    { Amount: 1520, Country: "United Kingdom", Date: "FY 2005", Product: "Car", Quantity: 93, State: "England" },
    { Amount: 1450, Country: "United Kingdom", Date: "FY 2007", Product: "Van", Quantity: 84, State: "England" },
    { Amount: 4930, Country: "United States", Date: "FY 2006", Product: "Van", Quantity: 59, State: "Alabama" },
    { Amount: 6250, Country: "United States", Date: "FY 2005", Product: "Bike", Quantity: 94, State: "Alabama" },
    { Amount: 1520, Country: "United States", Date: "FY 2006", Product: "Car", Quantity: 53, State: "North Carolina" },
    { Amount: 150, Country: "United States", Date: "FY 2008", Product: "Van", Quantity: 61, State: "North Carolina" },
    { Amount: 3200, Country: "United States", Date: "FY 2005", Product: "Bike", Quantity: 47, State: "South Carolina" },
    { Amount: 3900, Country: "United States", Date: "FY 2007", Product: "Car", Quantity: 43, State: "South Carolina" },
];