export let data: Object[] = [
    {
      OrderID: 10248,
      CustomerID: 'VINET',
      CustomerName: 'Maria ',
      OrderDate: new Date(8364186e5),
      ShippedDate: '1996-07-16T00:00:00.000Z',
      Freight: 32.38,
      ShipName: 'Vins et alcools Chevalier',
      ShipAddress: '59 rue de l Abbaye',
      ShipCity: 'Reims',
      ShipRegion: null,
      ShipCountry: 'France',
    },
    {
      OrderID: 10249,
      CustomerID: 'TOMSP',
      CustomerName: 'Ana Trujillo',
      OrderDate: new Date(836505e6),
      ShippedDate: '1996-07-10T00:00:00.000Z',
      Freight: 11.61,
      ShipName: 'Toms Spezialitäten',
      ShipAddress: 'Luisenstr. 48',
      ShipCity: 'Münster',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10250,
      CustomerID: 'HANAR',
      CustomerName: 'Antonio Moreno',
      OrderDate: new Date(8367642e5),
      ShippedDate: '1996-07-12T00:00:00.000Z',
      Freight: 65.83,
      ShipName: 'Hanari Carnes',
      ShipAddress: 'Rua do Paço, 67',
      ShipCity: 'Rio de Janeiro',
      ShipRegion: 'RJ',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10251,
      CustomerID: 'VICTE',
      CustomerName: 'Thomas Hardy',
      OrderDate: new Date(8367642e5),
      ShippedDate: '1996-07-15T00:00:00.000Z',
      Freight: 41.34,
      ShipName: 'Victuailles en stock',
      ShipAddress: '2, rue du Commerce',
      ShipCity: 'Lyon',
      ShipRegion: null,
      ShipCountry: 'France',
    },
    {
      OrderID: 10252,
      CustomerID: 'SUPRD',
      CustomerName: 'Christina Berglund',
      OrderDate: new Date(8368506e5),
      ShippedDate: '1996-07-11T00:00:00.000Z',
      Freight: 51.3,
      ShipName: 'Suprêmes délices',
      ShipAddress: 'Boulevard Tirou, 255',
      ShipCity: 'Charleroi',
      ShipRegion: null,
      ShipCountry: 'Belgium',
    },
    {
      OrderID: 10253,
      CustomerID: 'HANAR',
      CustomerName: 'Hanna Moos',
      OrderDate: new Date(8371098e5),
      ShippedDate: '1996-07-16T00:00:00.000Z',
      Freight: 58.17,
      ShipName: 'Hanari Carnes',
      ShipAddress: 'Rua do Paço, 67',
      ShipCity: 'Rio de Janeiro',
      ShipRegion: 'RJ',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10254,
      CustomerID: 'CHOPS',
      CustomerName: 'Frédérique Citeaux',
      OrderDate: new Date(837369e6),
      ShippedDate: '1996-07-23T00:00:00.000Z',
      Freight: 22.98,
      ShipName: 'Chop-suey Chinese',
      ShipAddress: 'Hauptstr. 31',
      ShipCity: 'Bern',
      ShipRegion: null,
      ShipCountry: 'Switzerland',
    },
    {
      OrderID: 10255,
      CustomerID: 'RICSU',
      CustomerName: 'Martín Sommer',
      OrderDate: new Date(8374554e5),
      ShippedDate: '1996-07-15T00:00:00.000Z',
      Freight: 148.33,
      ShipName: 'Richter Supermarkt',
      ShipAddress: 'Starenweg 5',
      ShipCity: 'Genève',
      ShipRegion: null,
      ShipCountry: 'Switzerland',
    },
    {
      OrderID: 10256,
      CustomerID: 'WELLI',
      CustomerName: 'Laurence Lebihan',
      OrderDate: new Date(8375418e5),
      ShippedDate: '1996-07-17T00:00:00.000Z',
      Freight: 13.97,
      ShipName: 'Wellington Importadora',
      ShipAddress: 'Rua do Mercado, 12',
      ShipCity: 'Resende',
      ShipRegion: 'SP',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10257,
      CustomerID: 'HILAA',
      CustomerName: 'Elizabeth Lincoln',
      OrderDate: new Date(8376282e5),
      ShippedDate: '1996-07-22T00:00:00.000Z',
      Freight: 81.91,
      ShipName: 'HILARION-Abastos',
      ShipAddress: 'Carrera 22 con Ave. Carlos Soublette #8-35',
      ShipCity: 'San Cristóbal',
      ShipRegion: 'Táchira',
      ShipCountry: 'Venezuela',
    },
    {
      OrderID: 10258,
      CustomerID: 'ERNSH',
      CustomerName: 'Victoria Ashworth',
      OrderDate: new Date(8377146e5),
      ShippedDate: '1996-07-23T00:00:00.000Z',
      Freight: 140.51,
      ShipName: 'Ernst Handel',
      ShipAddress: 'Kirchgasse 6',
      ShipCity: 'Graz',
      ShipRegion: null,
      ShipCountry: 'Austria',
    },
    {
      OrderID: 10259,
      CustomerID: 'CENTC',
      CustomerName: 'Patricio Simpson',
      OrderDate: new Date(8377146e5),
      ShippedDate: '1996-07-25T00:00:00.000Z',
      Freight: 3.25,
      ShipName: 'Centro comercial Moctezuma',
      ShipAddress: 'Sierras de Granada 9993',
      ShipCity: 'México D.F.',
      ShipRegion: null,
      ShipCountry: 'Mexico',
    },
    {
      OrderID: 10260,
      CustomerID: 'OTTIK',
      CustomerName: 'Francisco Chang',
      OrderDate: new Date(8379738e5),
      ShippedDate: '1996-07-29T00:00:00.000Z',
      Freight: 55.09,
      ShipName: 'Ottilies Käseladen',
      ShipAddress: 'Mehrheimerstr. 369',
      ShipCity: 'Köln',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
];

